// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyqssdzhwhwagdhxxews.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cXNzZHpod2h3YWdkaHh4ZXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDQ3ODYsImV4cCI6MjA2OTc4MDc4Nn0.7TLRvrxWgVh8xdrKiqEOeGik8hpbpkI6htgrmjGsug0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});